### ISSUE TITLE
Suspend issue

### ISSUE THREAD

**Issue by irvj** [Bert2Go/HPDevOne#32]
Is anyone else having issue with suspend on their Dev One? See here: https://github.com/pop-os/pop/issues/3078

Specifically, when I close the lid and come back later, the keyboard is mostly unresponsive. However, if I press the power button, the lock screen will come up displaying the time I closed it earlier, so some sort of freeze issue. I'm currently on HP Firmware 251985920 and haven't received any recent updates. This has been happening for a few weeks for me.

**Comment by Bert2Go** [comment]
Does this happen every time you suspend the computer by closing the lid? Or does it happen 'randomly' ?

**Comment by xancudo** [comment]
So, in my experience with the DevOne, I have seen similar issues when I shut the lid prior to disconnecting peripherals like an external keyboard and monitor, and then open it up later without those devices attached. So currently, I make it a point to pull everything, and then shut the lid.

**Comment by irvj** [comment]
@Bert2Go This has been happening daily for a couple weeks. Mostly I've noticed it when I use the machine after some hours between uses. If I close the lid, wait a few minutes, and open again, it's often fine. But if I open it in the morning when I get up, it's usually frozen or if I open it later on the in evening after I get home from work it's frozen. I really haven't been using it for very much lately, no new software added, just doing the usual system updates. For now, I've disabled suspend on close because I don't need to the power saving currently and I can be patient for a fix to roll out.

@xancudo I actually used mine in clamshell mode for 6+ months without issue, but recently moved and haven't fully setup my desk. So my Dev One has just been sitting by itself, no peripherals at all. This issue popped up within the past few weeks after I'm assuming a kernel update.

As much as I love Pop!_OS, I may just use this as an opportunity to test drive Fedora Silverblue for an extended period.

**Comment by irvj** [comment]
Just updating that my machine has been fine recently, so perhaps a kernel update fixed the issue. For the last month or so, I've been in clamshell mode 99% of the time, though. I'm planning a full system wipe soon just to start fresh. I'm going to close this for now.
