### ISSUE TITLE
Loose display hinge issue

### ISSUE THREAD

**Issue by grath90** [Bert2Go/HPDevOne#33]
Has anyone had an issue with the hinge? It has resistance opening and closing but it moves quite a bit in place.

**Comment by najamansari** [comment]
I have the same problem. The hinges have become quite loose. I'm probably
not going to attempt to fix it myself (lest I damage something) and take it
to a technician instead.

**Comment by grath90** [comment]
I emailed DevOne support and they responded with this:

To fix the issue with the hinge on the HP Dev One, you would need to purchase the HP EliteBook 845 G8 non-touch screen, disassembling the LCD assembly to access the hinge is not possible unfortunately.

We don't sell any parts for HP computers, you could check with HP Part Surfer for this: https://partsurfer.hp.com/partsurfer/
