### ISSUE TITLE
Coupon code doesn't work

### ISSUE THREAD

**Issue by davidskeck** [Bert2Go/HPDevOne#4]
Coupon code has expired

**Comment by Bert2Go** [comment]
Thank you for the heads up, I will remove it ... Actually it seems like the option to add a coupon code during checkout has been removed ...

**Comment by Bert2Go** [comment]
A new Coupon Code is available @davidskeck , you can find it in the [guide](https://github.com/Bert2Go/HPDevOne#coupon-code).

**Comment by davidskeck** [comment]
Wow! thanks for the heads up!
