### ISSUE TITLE
How is the support for battery limit charging

### ISSUE THREAD

**Issue by aeros281** [Bert2Go/HPDevOne#5]
One popular feature on dev laptop is the ability to stop charging when the battery percent reach some value, for example: 50%, 55% or 80%.  This is to protect battery in case the machine is plugged in for a very long time.

My old HP laptop does not have this feature, so I want to know if Dev One support it or not.

**Comment by Bert2Go** [comment]
Hi @aeros281 it looks like it has a option in the BIOS: Configuration -> [Adaptive Battery Optimizer](https://support.hp.com/us-en/document/c06310986), from what I understand it is a technology developed by HP to Prolong Battery Life Span. Unfortunately I do NOT see any option to set the battery percentage, and there is no setting within  POP!_OS. I created a post [here](https://www.reddit.com/r/System76/comments/x6jnqn/will_there_be_battery_limit_support_for_the_hp/) hoping to get some more information about this issue.

**Comment by aeros281** [comment]
I see, so the option in BIOS is kind of the same as the one on macOS (kind of smart, kind of dumb) since it depends on usage pattern instead of letting the user to manually limit the charging behavior.

**Comment by Bert2Go** [comment]
I am keeping this issue open, just in case we are hearing back from System76/HP

**Comment by Bert2Go** [comment]
Unfortunately no response from HP. System76 said it would need to be supported from the hardware in order to work.
At this point I am closing this issue. I hope there will be a next generation of this laptop with battery limit charge support.
