### ISSUE TITLE
Corsair Vengeance memory is not recognized.

### ISSUE THREAD

**Issue by lkurz** [Bert2Go/HPDevOne#6]
Corsair Vengeance Performance DDR4 64GB kit (2x32GB) 3200MHz PC4-25600 CL22 Non-ECC 1.2V SO-DIMM 260-Pin
P/N CMSX64GX4M2A3200C22 
is not being recognized by my HP DEVONE laptops./
We have tried two 64Gb kits from different sources and neither worked.

Display backlit but no system activity.  On one of our restarts it flashed a pop_os warning or error, but we were unable to capture or repeat. 

No issues with Crucial CT32G4SFD8322A.C16FF (2x32GB DDR4-3200 SODIMM 1.2V CL22) memory kits.

**Comment by Bert2Go** [comment]
Hi @lkurz thank you for your feedback. I am surprised the read that about the Corsair Vengeance 2x32GB Kit ! I have been told by an HP Dev One Owner that the Vengeance Performance Sticks worked. I will take them out of the Guide and replace them with the ones you are mentioning. I personally have the TeamGroup ones and they work like a charm.
I will keep this ticket open until the update to the guide is made.

**Comment by Bert2Go** [comment]
@lkurz can you confirm if the following are the memory sticks you are referring to ?
I am not finding anything under the string you mentioned: CT32G4SFD8322A.C16FF
I did however find these, if you can see if those are the ones you are referring to, then I can add them to the Guide.
https://www.newegg.com/crucial-64gb-260-pin-ddr4-so-dimm/p/20-156-242

**Comment by Bert2Go** [comment]
@lkurz It seems like it is the memory you used. Adding it to the Guide while also removing the Vengeance 64GB Kit. 
Appreciate your contribution.
ps: Should it be the wrong memory I am referencing, please let me know.
