### ISSUE TITLE
Adaptive Battery Optmizer

### ISSUE THREAD

**Issue by afsilva** [Bert2Go/HPDevOne#8]
I saw you guys were asking on what it is -- I found this: https://support.hp.com/us-en/document/c06310986

-- I think on the HP Dev One it shows how even though sometimes your are plugged in, you can see the battery not charging... as a way to not waste battery cycles (a guess).

**Comment by Bert2Go** [comment]
Yes that is correct. It seems like it stops charging while in the higher 90s battery percentage values. 
Appreciate the information, thank you.

**Comment by Bert2Go** [comment]
@afsilva Added your info to the Guide https://github.com/Bert2Go/HPDevOne#adaptive-battery-optimizer
Thank you for your ontribution
